ungrouped:
  hosts:
    managedhost-app-1:
      ansible_host: 0.0.0.0
      ansible_port: 2223
      ansible_user: root
      ansible_connection: ssh
    managedhost-app-2:
      ansible_host: 0.0.0.0
      ansible_port: 2224
      ansible_user: root
      ansible_connection: ssh
    managedhost-app-3:
      ansible_host: 0.0.0.0
      ansible_port: 2225
      ansible_user: root
      ansible_connection: ssh
app_group:
  hosts:
    managedhost-app-1:
    managedhost-app-2:
    managedhost-app-3:
  load_balancer:
    localhost:
